apiVersion: v1
kind: Service
metadata:
  name: {{ include "coda.fullname" . }}
  labels:
    {{- include "coda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    {{- include "coda.selectorLabels" . | nindent 4 }}
